LPRNet:
  TRAIN:
    NUM_EPOCHS: 100
    SAVE_PERIOD: 2
    PRETRAINED_MODEL: '/home/max/Data/License_Plate_Recognition/models/Final_LPRNet_model.pth'
    PRETRAINED_SPATIAL_TRANSFORMER: '/home/max/Data/License_Plate_Recognition/models/Final_STN_model.pth'
LPR_dataset:
  TRAIN_FOLDER: 'test_run'
  VAL_FOLDER: 'test_run'